# 静的型安全性を最優先としたSwiftLint設定
# Type Safety First SwiftLint Configuration

disabled_rules:
  - trailing_whitespace
  - strict_fileprivate
  - explicit_self
  - explicit_type_interface
  - implicit_return
  - trailing_closure
  - discouraged_optional_boolean
  - discouraged_optional_collection

# 静的型安全性に関する厳格なルール（Strict Type Safety Rules）
opt_in_rules:
  # 必須の型安全性ルール（Essential Type Safety Rules）
  - force_unwrapping                    # Force unwrapping禁止
  - force_try                          # Force try禁止  
  - force_cast                         # Force cast禁止
  - implicitly_unwrapped_optional       # 暗黙的unwrapped optional禁止
  
  # Optional関連の型安全性ルール（Optional Safety Rules）
  - redundant_nil_coalescing           # 冗長なnil coalescingの検出
  - shorthand_optional_binding         # 簡潔なoptional binding推奨
  - optional_enum_case_matching        # Optional enum case matching最適化
  
  # エラーハンドリング関連（Error Handling Safety）
  - untyped_error_in_catch             # 型付きエラーハンドリング推奨
  
  # その他有用なルール（Other Useful Rules）
  - empty_count                        # .isEmpty推奨
  - fallthrough                        # fallthrough文の明示的記述
  - identical_operands                 # 同一オペランドの検出
  - unavailable_function               # 非推奨関数の検出
  - overridden_super_call             # super呼び出しの確認

included:
  - ActivityMonitorIRL

excluded:
  - Carthage
  - Pods
  - .build

line_length:
  warning: 150
  error: 180

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_parameter_count:
  warning: 6
  error: 8

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50

# 型安全性ルールの重要度設定（Type Safety Rule Severity）
force_unwrapping: error              # Force unwrappingは絶対に許可しない
force_try: error                     # Force tryは絶対に許可しない
force_cast: error                    # Force castは絶対に許可しない
implicitly_unwrapped_optional: error  # 暗黙的unwrapped optionalは警告レベル

# Optional関連ルールの重要度
redundant_nil_coalescing: warning

reporter: "xcode"
